import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

import { Clapperboard, Play } from "lucide-react";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

import { GenreType } from "@/types/global";
import { redirect } from "next/navigation";

async function fetchGenres(): Promise<GenreType[]> {
    const res = await fetch("https://api.themoviedb.org/3/genre/movie/list", {
        headers: {
            Authorization: `Bearer ${process.env.TMDB_TOKEN}`
        }
    });

    const data = await res.json();
    return data.genres;
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
    const genres = await fetchGenres();

	async function search(formData:FormData) {
		"use server"
		const q=formData.get("q")
		redirect(`/search?q=${q}`)
	}

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div>
					<header className="p-4 border-b flex justify-between items-center">
						<h1 className="text-2xl font-bold flex gap-2 items-center">
							<Clapperboard size={24} />
							Next Movie
						</h1>
						<form action={search } className="flex gap-1">
							<Input name="q" />
							<Button type="submit">Search</Button>
						</form>
					</header>
					<section className="flex">
						<aside className="w-[200px] p-4 border-r flex flex-col gap-1">
							<Button
                asChild
								variant="outline">
								<Link
                href="/"
                className="flex justify-start gap-2 items-center">
								<Play />
								All Movies
                </Link>
							</Button>
							{genres.map(genre => {
								return (
									<Button
                  asChild
										key={genre.id}
										variant="outline">
										<Link
                    className="flex justify-start gap-2 items-center"
                    href={`/gener/${genre.name}/${genre.id}`}>
										<Play />
										{genre.name}
                    </Link>
									</Button>
								);
							})}
						</aside>
						<main className="flex-1 p-4">{children}</main>
					</section>
				</div>
			</body>
		</html>
	);
}